### ISSUE TITLE
ModuleNotFoundError: No module named 'jaxstar.mistfit.mistgrid'

### ISSUE THREAD

**Issue by ahlamaq** [kemasuda/jaxstar#4]
I am trying to run the demo "isochrone fitting example.ipynb" on my machine (Apple M3), and I get a module error when trying to import the package. I successfully installed the package itself and it was added as a site package in my anaconda distribution. The error message is copied below:

`Traceback (most recent call last):`
  `File "jaxstar_ages.py", line 1, in <module>`
    `from jaxstar import mistfit`
  `File "/anaconda3/lib/python3.11/site-packages/jaxstar-0.1.0-py3.11.egg/jaxstar/__init__.py", line 10, in <module>`
    `from . import mistfit`
  `File "/anaconda3/lib/python3.11/site-packages/jaxstar-0.1.0-py3.11.egg/jaxstar/mistfit/__init__.py", line 1, in <module>`
    `from .mistfit import *`
  `File "/anaconda3/lib/python3.11/site-packages/jaxstar-0.1.0-py3.11.egg/jaxstar/mistfit/mistfit.py", line 15, in <module>`
    `from jaxstar.mistfit.mistgrid.create_grid import *`
`ModuleNotFoundError: No module named 'jaxstar.mistfit.mistgrid'`

When I checked the directory, indeed the "mistgrid" folder was missing from the "misfit" folder. While it is there in the downloaded zip file of the package, running `python setup.py install` somehow excludes it when it adds the package to the anaconda distribution. I manually added the "mistgrid" module from the downloaded zip folder of the package and it fixed the issue, but it might be good to check why the `python setup.py install` command excludes it during installation.

**Comment by kemasuda** [comment]
Also thank you for this report, I'm not sure about the reason right away but I will look into it further.
